# This is a basic workflow that is manually triggered

name: Java CI

on:
  push:
    branches: [ Unstable ]
  pull_request:
    branches: [ Unstable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml jars
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: build
        path: /home/runner/work/ArdClient/ArdClient/build/
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: /home/runner/work/ArdClient/ArdClient/build/
